/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.choice;

import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.FlowLayout;

import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.MenuElement;
import javax.swing.MenuSelectionManager;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Christopher
 */
public class View_Test2 extends javax.swing.JFrame {

      /**
       * Creates new form View_Test
       */
      public View_Test2() {
            setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            
            JPanel newPanel = new JPanel();
            newPanel.setLocation(6, 6);
            newPanel.setSize(700, 500);
            newPanel.setBackground(new Color(0,0,0));
            
            JFrame newFrame = new JFrame();
            
            newFrame.setLocation(100, 100);
            newFrame.setSize(800, 600);
            newFrame.setUndecorated(true);
            newFrame.add(newPanel);
            newFrame.setVisible(true);
            
            Container cp = getContentPane();
            cp.setLayout(new FlowLayout());

            JMenuBar mb = new JMenuBar();
            setJMenuBar(mb);

            JMenu om = new JMenu("Options");
            JMenu opSubm = new JMenu("SubOptions");
            opSubm.add(new JMenuItem("Alpha"));
            opSubm.add(new JMenuItem("Gamma"));
            opSubm.add(new JMenuItem("Delta"));
            om.add(opSubm);
            mb.add(om);
            
            

            MenuSelectionManager.defaultManager().addChangeListener(
                    new ChangeListener() {
                  public void stateChanged(ChangeEvent evt) {
                        
                        
                        System.out.println("PATH: "+ MenuSelectionManager.defaultManager().getSelectedPath());
                        System.out.println("TEXT: "+ om.getText());
                        /*
                        MenuElement[] path = MenuSelectionManager.defaultManager()
                                .getSelectedPath();

                        if (path.length == 0) {
                              System.out.println("No menus are opened or menu items selected");
                        }
                        for (int i = 0; i < path.length; i++) {
                              Component c = path[i].getComponent();
                              System.out.println("Component: "+c);

                              if (c instanceof JMenuItem) {
                                    JMenuItem mi = (JMenuItem) c;
                                    
                                    System.out.println("mi: "+mi);
                                    JMenuItem mi2 = new JMenuItem();
                                    System.out.println("mi.getText(): "+mi.getText());
                              }
                        }
                        */
                  }
            });

      }

      /**
       * This method is called from within the constructor to initialize the
       * form. WARNING: Do NOT modify this code. The content of this method is
       * always regenerated by the Form Editor.
       */
      @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            jMenuItem2 = new javax.swing.JMenuItem();
            jPanel1 = new javax.swing.JPanel();

            jMenuItem2.setText("jMenuItem2");

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            jPanel1.setBackground(new java.awt.Color(0, 0, 0));

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                  jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGap(0, 594, Short.MAX_VALUE)
            );
            jPanel1Layout.setVerticalGroup(
                  jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGap(0, 310, Short.MAX_VALUE)
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(72, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
            );

            pack();
      }// </editor-fold>//GEN-END:initComponents

      /**
       * @param args the command line arguments
       */
      public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                  for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                              javax.swing.UIManager.setLookAndFeel(info.getClassName());
                              break;
                        }
                  }
            } catch (ClassNotFoundException ex) {
                  java.util.logging.Logger.getLogger(View_Test2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                  java.util.logging.Logger.getLogger(View_Test2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                  java.util.logging.Logger.getLogger(View_Test2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                  java.util.logging.Logger.getLogger(View_Test2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                  public void run() {
                        new View_Test2().setVisible(true);
                  }
            });
      }

      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JMenuItem jMenuItem2;
      private javax.swing.JPanel jPanel1;
      // End of variables declaration//GEN-END:variables
}
